@startuml "team"
skinparam style strictuml

actor Admin
boundary HalamanTim as View
control TeamController as Controller
collections Team as Collection

Admin -> View ++ : Mengakses halaman team
  View -> Controller ++: onMounted
    Controller -> Collection ++ : get()
    return data
  return Menampilkan data team
return

Admin -> View ++ : Klik Tambah Tim
  View -> Controller ++: onClick
    Controller -> Collection ++ : add()
    return data
  return Menampilkan data team
return

@enduml